name: rvf-nextstrain
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # Core Python
  - python=3.10
  # Nextstrain tools
  - nextstrain-cli=5.0.0
  - augur=21.1.0
  - auspice=3.0.2
  - snakemake=7.32.4
  # Dependencies for sequence analysis
  - mafft=7.520
  - iqtree=2.2.2.7
  # Python libraries
  - biopython=1.82
  - pandas=2.1.2
  - pyyaml=6.0.1
  - jsonschema=4.19.1
  - pytest=7.4.3
  - requests=2.31.0
  - git
