# Master configuration file with enhanced workflow options
active_pathogen: "rvf"

# Pathogen registry
pathogens:
  rvf:
    name: "Rift Valley Fever virus"
    config_path: "pathogens/rvf/config/config.yaml"
    auspice_config_path: "pathogens/rvf/config/auspice_config.json"
    lat_longs_path: "pathogens/rvf/config/lat_longs.tsv"
    has_segments: true

  # Template for adding a new pathogen (e.g., cholera)
  # cholera:
  #   name: "Vibrio cholerae"
  #   config_path: "pathogens/cholera/config/config.yaml"
  #   auspice_config_path: "pathogens/cholera/config/auspice_config.json"
  #   lat_longs_path: "pathogens/cholera/config/lat_longs.tsv"
  #   has_segments: false

# Common configuration parameters
common:
  filter:
    max_n: 100
    exclude_ids: []
    exclude_where: []

  subsample:
    priorities:
      recency:
        type: "numeric"
        field: "num_date"

  update:
    frequency: "weekly"
    incremental: true
    archive:
      enabled: true

  qc:
    nextclade:
      enabled: true
      min_qc_score: 80
      max_missing_data: 0.05
      max_mut_clusters: 3
      exclude_clades: []
    reporting:
      enabled: true
      output_dir: "results/qc_reports"

  # New workflow management parameters
  workflow:
    strict_metadata: false # Whether to enforce strict metadata validation
    fail_on_invalid: false # Whether to fail the workflow if invalid metadata found
    create_combined_view: true # For multi-segment analyses, create a combined view
    use_checkpoints: true # Enable checkpoint-based workflow control
    save_intermediates: true # Save intermediate files for debugging
    notification: # Notification settings for automated runs
      enabled: true
      email: "your.email@example.com" # Optional: email address
      slack_webhook: "https://hooks.slack.com/services/..." # Optional: Slack webhook URL

  # Resource specifications for scaling
  resources:
    download:
      mem_mb: 2000
      runtime: 60 # minutes
    metadata:
      mem_mb: 2000
      runtime: 30
    filter:
      mem_mb: 2000
    align:
      threads: 4
      mem_mb: 4000
    tree:
      threads: 4
      mem_mb: 8000
    refine:
      threads: 2
      mem_mb: 4000
    traits:
      mem_mb: 2000
    export:
      mem_mb: 2000
    nextclade:
      threads: 2
      mem_mb: 4000
    qc_report:
      mem_mb: 2000
    split_segments:
      mem_mb: 2000
    combine:
      mem_mb: 2000
    combined_qc:
      mem_mb: 2000

    # Performance monitoring resources
    performance_report:
      mem_mb: 2000
      runtime: 15
    monitoring_dashboard:
      mem_mb: 2000
      runtime: 10

  # Backup configuration
  backup:
    enabled: true
    directory: "backups"
    retention_days: 30
    retention_count: 10
    compression: true
    max_age: 7 # Maximum acceptable age in days for monitoring
    alert_email: "your.email@example.com"
    schedule:
      after_build: true
      weekly_full: true
      weekly_day: "Sunday"

  # Add the export configuration
  export:
    node_data:
      - "nt_muts"
      - "branch_lengths"
      - "traits"
    extra_node_data: [] # Optional additional node data files
    colors: null # Optional path to colors file
