# Pathogen-specific configuration for Rift Valley Fever virus

# Data options
data:
  search_term: "Rift Valley fever virus[organism] OR Phlebovirus riftense[organism]"
  max_sequences: 500
  segment: "all" # Use "all" for multi-segment analysis, or "L", "M", or "S" for single segment

  # Optional segment-specific reference sequences
  reference_sequence:
    L: "pathogens/rvf/references/L_reference.fasta"
    M: "pathogens/rvf/references/M_reference.fasta"
    S: "pathogens/rvf/references/S_reference.fasta"

# Filter parameters
filter:
  exclude_where:
    - "host = ''" # Exclude entries with empty host field
    - "date = ''" # Exclude entries with empty date field

# Refinement parameters
refine:
  coalescent: "opt"
  clock_rate: "" # Leave empty for auto estimation, or specify value

# Traits to reconstruct
traits:
  columns: ["country", "host"]

# Subsampling parameters
subsample:
  max_sequences: 300
  group_by: "country year"
  priorities:
    host:
      type: "categorical"
      focus:
        - "Homo sapiens"
        - "Ovis aries"
        - "Bos taurus"

# Resources (pathogen-specific overrides)
resources:
  align:
    threads: 8 # Use more threads for RVF alignment
    mem_mb: 8000
  tree:
    threads: 8 # Use more threads for RVF tree building
    mem_mb: 16000

# Advanced phylogenetics configuration (RVF-specific)
advanced_phylogenetics:
  enabled: true
  alignment:
    methods: ["mafft", "muscle", "biopython"] # Prefer MAFFT for RVF
    auto_select: true
    quality_threshold: 0.8 # Higher threshold for RVF
  tree_building:
    methods: ["iqtree", "nj", "mp"] # Prefer IQ-TREE for RVF
    auto_select: true
    bootstrap_replicates: 1000 # More replicates for RVF
  temporal_analysis:
    enabled: true
    molecular_clock: true
    date_formats: ["YYYY-MM-DD", "DD-MMM-YYYY", "YYYY-MM", "YYYY"] # Support NCBI formats
    temporal_resolution: "month"
  quality_control:
    min_sequences: 5 # Minimum for meaningful phylogenetic analysis
    max_gaps: 0.9 # Allow some gaps for RVF sequences
    alignment_length_threshold: 500 # Minimum alignment length
  output:
    save_intermediates: true
    generate_reports: true
    export_json: true

# Segment-specific settings
segments: ["L", "M", "S"]
