name: Deploy Nextstrain Dashboard to GitHub Pages

on:
  push:
    branches: [main]
    paths:
      - "auspice/**"
      - "deploy/**"
  workflow_dispatch: # Allow manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Verify Auspice JSON files exist
        run: |
          echo "Checking for Auspice JSON files..."
          ls -la auspice/

          # Validate JSON files
          for file in auspice/*.json; do
            echo "Validating $file..."
            if python3 -m json.tool "$file" > /dev/null 2>&1; then
              echo "✓ $file is valid JSON"
            else
              echo "✗ $file is invalid JSON"
              exit 1
            fi
          done

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Create dashboard deployment
        run: |
          echo "Creating dashboard deployment..."

          # Create build directory
          mkdir -p build

          # Copy JSON files to build directory for direct access
          cp auspice/*.json build/

          # Create main index.html that links to the actual dashboards
          cat > build/index.html << 'EOF'
          <!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>RVF Nextstrain Dashboard</title>
              <style>
                  body { 
                      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
                      max-width: 800px; 
                      margin: 2rem auto; 
                      padding: 1rem; 
                      background: #f8f9fa;
                      line-height: 1.6;
                  }
                  .container { 
                      background: white; 
                      padding: 2rem; 
                      border-radius: 12px; 
                      box-shadow: 0 4px 6px rgba(0,0,0,0.1); 
                  }
                  .dashboard-link { 
                      display: block; 
                      padding: 1.5rem; 
                      margin: 1rem 0; 
                      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                      border: none;
                      border-radius: 8px; 
                      text-decoration: none; 
                      color: white;
                      transition: all 0.3s ease;
                      box-shadow: 0 2px 4px rgba(0,0,0,0.1);
                  }
                  .dashboard-link:hover { 
                      transform: translateY(-2px);
                      box-shadow: 0 4px 8px rgba(0,0,0,0.2);
                  }
                  h1 { 
                      color: #2c3e50; 
                      text-align: center;
                      margin-bottom: 2rem;
                      font-size: 2.5rem;
                  }
                  .desc { 
                      font-size: 0.9em; 
                      opacity: 0.9; 
                      margin-top: 0.5rem; 
                  }
                  .status {
                      background: #d4edda;
                      border: 1px solid #c3e6cb;
                      border-radius: 8px;
                      padding: 1rem;
                      margin: 1rem 0;
                      color: #155724;
                      text-align: center;
                  }
                  .nextstrain-link {
                      display: block;
                      padding: 1rem;
                      margin: 0.5rem 0;
                      background: #f8f9fa;
                      border: 2px solid #007bff;
                      border-radius: 8px;
                      text-decoration: none;
                      color: #007bff;
                      text-align: center;
                  }
                  .nextstrain-link:hover {
                      background: #e9ecef;
                  }
              </style>
          </head>
          <body>
              <div class="container">
                  <h1>🦠 Rift Valley Fever<br>Nextstrain Dashboard</h1>
                  
                  <div class="status">
                      <strong>✅ Interactive dashboards are ready!</strong><br>
                      Click below to explore phylogenetic analyses of RVF virus segments.
                  </div>
                  
                  <p style="text-align: center; font-size: 1.1em; margin: 2rem 0;">
                      <strong>Genomic surveillance and phylogenetic analysis of Rift Valley Fever virus segments</strong>
                  </p>
                  
                  <a href="https://nextstrain.org/fetch/gkamundia.github.io/Phylos/rvf_L.json" class="dashboard-link" target="_blank">
                      <strong>🧬 RVF Segment L (Large)</strong>
                      <div class="desc">RNA-dependent RNA polymerase gene - Largest genomic segment</div>
                  </a>
                  
                  <a href="https://nextstrain.org/fetch/gkamundia.github.io/Phylos/rvf_M.json" class="dashboard-link" target="_blank">
                      <strong>🧬 RVF Segment M (Medium)</strong>
                      <div class="desc">Glycoprotein genes (Gn, Gc) and NSm protein</div>
                  </a>
                  
                  <a href="https://nextstrain.org/fetch/gkamundia.github.io/Phylos/rvf_S.json" class="dashboard-link" target="_blank">
                      <strong>🧬 RVF Segment S (Small)</strong>
                      <div class="desc">Nucleocapsid protein and NSs protein genes</div>
                  </a>
                  
                  <div style="margin: 2rem 0; padding: 1rem; background: #fff3cd; border-radius: 8px;">
                      <p><strong>💡 Alternative viewing options:</strong></p>
                      <a href="rvf_L.json" class="nextstrain-link" download>📥 Download L segment JSON</a>
                      <a href="rvf_M.json" class="nextstrain-link" download>📥 Download M segment JSON</a>
                      <a href="rvf_S.json" class="nextstrain-link" download>📥 Download S segment JSON</a>
                      <p style="font-size: 0.9em; margin-top: 1rem; color: #856404;">
                          Download files and drag them to <a href="https://auspice.us" target="_blank">auspice.us</a> for offline viewing.
                      </p>
                  </div>
                  
                  <div style="text-align: center; margin-top: 3rem; padding-top: 2rem; border-top: 1px solid #ddd; color: #6c757d;">
                      <p>Built with <strong>Nextstrain</strong> | 
                      <a href="https://github.com/GKamundia/Phylos" target="_blank" style="color: #007bff;">View Source Code</a></p>
                      <p style="font-size: 0.9em;">Interactive phylogenetic visualization powered by Auspice</p>
                  </div>
              </div>
          </body>
          </html>
          EOF
          
          echo "✅ Dashboard deployment created"
          echo "📂 Build contents:"
          ls -la build/
          echo ""
          echo "🔍 JSON files available:"
          find build/ -name "*.json" | head -10

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./build"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
